// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "message": message Resource Client
//
// Command:
// $ goagen
// --design=github.com/golang-test/src/message/design
// --out=$(GOPATH)/src/github.com/golang-test
// --version=v1.3.1

package client

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strconv"
)

// ShowMessagePath computes a request path to the show action of message.
func ShowMessagePath(roomID int) string {
	param0 := strconv.Itoa(roomID)

	return fmt.Sprintf("/messages/%s", param0)
}

// Get messages by Room ID
func (c *Client) ShowMessage(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewShowMessageRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewShowMessageRequest create the request corresponding to the show action endpoint of the message resource.
func (c *Client) NewShowMessageRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}
