consumes:
- application/json
- application/xml
- application/gob
- application/x-gob
definitions:
  GoaExampleMessage:
    description: A message of room (default view)
    example:
      href: Rerum rerum dignissimos nostrum quia.
      id: 5368818320236413418
      message: Veniam excepturi.
    properties:
      href:
        description: API href for making requests on the message
        example: Rerum rerum dignissimos nostrum quia.
        type: string
      id:
        description: Unique Message ID
        example: 5368818320236413418
        format: int64
        type: integer
      message:
        description: Sentence of Message
        example: Veniam excepturi.
        type: string
    required:
    - id
    - href
    - message
    title: 'Mediatype identifier: application/vnd.goa.example.message+json; view=default'
    type: object
host: localhost:8080
info:
  description: This is the Message API
  title: The Message API
  version: ""
paths:
  /messages/{roomId}:
    get:
      description: Get messages by Room ID
      operationId: message#show
      parameters:
      - description: Room ID
        in: path
        name: roomId
        required: true
        type: integer
      produces:
      - application/vnd.goa.example.message+json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/GoaExampleMessage'
        "404":
          description: Not Found
      schemes:
      - http
      summary: show message
      tags:
      - message
produces:
- application/json
- application/xml
- application/gob
- application/x-gob
responses:
  NotFound:
    description: Not Found
  OK:
    description: OK
    schema:
      $ref: '#/definitions/GoaExampleMessage'
schemes:
- http
swagger: "2.0"
