// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "message": Application Contexts
//
// Command:
// $ goagen
// --design=github.com/golang-test/src/message/design
// --out=$(GOPATH)/src/github.com/golang-test
// --version=v1.3.1

package app

import (
	"context"
	"github.com/goadesign/goa"
	"net/http"
	"strconv"
)

// ShowMessageContext provides the message show action context.
type ShowMessageContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
	RoomID int
}

// NewShowMessageContext parses the incoming request URL and body, performs validations and creates the
// context used by the message controller show action.
func NewShowMessageContext(ctx context.Context, r *http.Request, service *goa.Service) (*ShowMessageContext, error) {
	var err error
	resp := goa.ContextResponse(ctx)
	resp.Service = service
	req := goa.ContextRequest(ctx)
	req.Request = r
	rctx := ShowMessageContext{Context: ctx, ResponseData: resp, RequestData: req}
	paramRoomID := req.Params["roomId"]
	if len(paramRoomID) > 0 {
		rawRoomID := paramRoomID[0]
		if roomID, err2 := strconv.Atoi(rawRoomID); err2 == nil {
			rctx.RoomID = roomID
		} else {
			err = goa.MergeErrors(err, goa.InvalidParamTypeError("roomId", rawRoomID, "integer"))
		}
	}
	return &rctx, err
}

// OK sends a HTTP response with status code 200.
func (ctx *ShowMessageContext) OK(r *GoaExampleMessage) error {
	if ctx.ResponseData.Header().Get("Content-Type") == "" {
		ctx.ResponseData.Header().Set("Content-Type", "application/vnd.goa.example.message+json")
	}
	return ctx.ResponseData.Service.Send(ctx.Context, 200, r)
}

// NotFound sends a HTTP response with status code 404.
func (ctx *ShowMessageContext) NotFound() error {
	ctx.ResponseData.WriteHeader(404)
	return nil
}
