// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "message": Application User Types
//
// Command:
// $ goagen
// --design=github.com/golang-test/src/message/design
// --out=$(GOPATH)/src/github.com/golang-test
// --version=v1.3.1

package app
